version: '3'
services:
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    container_name: biconnect_backend
    ports:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./BiConnectBE:/code/
    depends_on:
      - database
    network_mode: host
    environment:
      EMAIL_HOST: host_like_smtp.gmail.com
      EMAIL_HOST_USER: email_address@domaain.com
      EMAIL_HOST_PASSWORD: email_password

  frontend:
    image: node:latest
    container_name: biconnect_frontend
    ports:
      - 3000
    volumes:
      - ./BiConnectFE:/code/
    working_dir: /code
    entrypoint: bash -c "yarn install && yarn run dev"
    network_mode: host

  database:
    image: postgres
    container_name: biconnect_database
    restart: always
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_USER: devDB
    network_mode: host
